# Generated by Django 3.2.6 on 2021-08-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cars',
            unique_together={('make', 'model')},
        ),
    ]
