# Generated by Django 3.2.6 on 2021-08-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_alter_cars_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car_Ratings',
            new_name='CarRatings',
        ),
    ]
