# Generated by Django 3.2.6 on 2021-08-23 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_rename_car_ratings_carratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carratings',
            name='rating',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
